#!/bin/bash
# To be run from project root, i.e. 
bash ./plop/runplop.sh championClass Aatrox
bash ./plop/runplop.sh championClass Ahri
bash ./plop/runplop.sh championClass Akali
bash ./plop/runplop.sh championClass Akshan
bash ./plop/runplop.sh championClass Alistar
bash ./plop/runplop.sh championClass Amumu
bash ./plop/runplop.sh championClass Anivia
bash ./plop/runplop.sh championClass Annie
bash ./plop/runplop.sh championClass Aphelios
bash ./plop/runplop.sh championClass Ashe
bash ./plop/runplop.sh championClass AurelionSol
bash ./plop/runplop.sh championClass Azir
bash ./plop/runplop.sh championClass Bard
bash ./plop/runplop.sh championClass Belveth
bash ./plop/runplop.sh championClass Blitzcrank
bash ./plop/runplop.sh championClass Brand
bash ./plop/runplop.sh championClass Braum
bash ./plop/runplop.sh championClass Briar
bash ./plop/runplop.sh championClass Caitlyn
bash ./plop/runplop.sh championClass Camille
bash ./plop/runplop.sh championClass Cassiopeia
bash ./plop/runplop.sh championClass Chogath
bash ./plop/runplop.sh championClass Corki
bash ./plop/runplop.sh championClass Darius
bash ./plop/runplop.sh championClass Diana
bash ./plop/runplop.sh championClass Draven
bash ./plop/runplop.sh championClass DrMundo
bash ./plop/runplop.sh championClass Ekko
bash ./plop/runplop.sh championClass Elise
bash ./plop/runplop.sh championClass Evelynn
bash ./plop/runplop.sh championClass Ezreal
bash ./plop/runplop.sh championClass Fiddlesticks
bash ./plop/runplop.sh championClass Fiora
bash ./plop/runplop.sh championClass Fizz
bash ./plop/runplop.sh championClass Galio
bash ./plop/runplop.sh championClass Gangplank
bash ./plop/runplop.sh championClass Garen
bash ./plop/runplop.sh championClass Gnar
bash ./plop/runplop.sh championClass Gragas
bash ./plop/runplop.sh championClass Graves
bash ./plop/runplop.sh championClass Gwen
bash ./plop/runplop.sh championClass Hecarim
bash ./plop/runplop.sh championClass Heimerdinger
bash ./plop/runplop.sh championClass Illaoi
bash ./plop/runplop.sh championClass Irelia
bash ./plop/runplop.sh championClass Ivern
bash ./plop/runplop.sh championClass Janna
bash ./plop/runplop.sh championClass JarvanIV
bash ./plop/runplop.sh championClass Jax
bash ./plop/runplop.sh championClass Jayce
bash ./plop/runplop.sh championClass Jhin
bash ./plop/runplop.sh championClass Jinx
bash ./plop/runplop.sh championClass Kaisa
bash ./plop/runplop.sh championClass Kalista
bash ./plop/runplop.sh championClass Karma
bash ./plop/runplop.sh championClass Karthus
bash ./plop/runplop.sh championClass Kassadin
bash ./plop/runplop.sh championClass Katarina
bash ./plop/runplop.sh championClass Kayle
bash ./plop/runplop.sh championClass Kayn
bash ./plop/runplop.sh championClass Kennen
bash ./plop/runplop.sh championClass Khazix
bash ./plop/runplop.sh championClass Kindred
bash ./plop/runplop.sh championClass Kled
bash ./plop/runplop.sh championClass KogMaw
bash ./plop/runplop.sh championClass KSante
bash ./plop/runplop.sh championClass Leblanc
bash ./plop/runplop.sh championClass LeeSin
bash ./plop/runplop.sh championClass Leona
bash ./plop/runplop.sh championClass Lillia
bash ./plop/runplop.sh championClass Lissandra
bash ./plop/runplop.sh championClass Lucian
bash ./plop/runplop.sh championClass Lulu
bash ./plop/runplop.sh championClass Lux
bash ./plop/runplop.sh championClass Malphite
bash ./plop/runplop.sh championClass Malzahar
bash ./plop/runplop.sh championClass Maokai
bash ./plop/runplop.sh championClass MasterYi
bash ./plop/runplop.sh championClass Milio
bash ./plop/runplop.sh championClass MissFortune
bash ./plop/runplop.sh championClass MonkeyKing
bash ./plop/runplop.sh championClass Mordekaiser
bash ./plop/runplop.sh championClass Morgana
bash ./plop/runplop.sh championClass Naafiri
bash ./plop/runplop.sh championClass Nami
bash ./plop/runplop.sh championClass Nasus
bash ./plop/runplop.sh championClass Nautilus
bash ./plop/runplop.sh championClass Neeko
bash ./plop/runplop.sh championClass Nidalee
bash ./plop/runplop.sh championClass Nilah
bash ./plop/runplop.sh championClass Nocturne
bash ./plop/runplop.sh championClass Nunu
bash ./plop/runplop.sh championClass Olaf
bash ./plop/runplop.sh championClass Orianna
bash ./plop/runplop.sh championClass Ornn
bash ./plop/runplop.sh championClass Pantheon
bash ./plop/runplop.sh championClass Poppy
bash ./plop/runplop.sh championClass Pyke
bash ./plop/runplop.sh championClass Qiyana
bash ./plop/runplop.sh championClass Quinn
bash ./plop/runplop.sh championClass Rakan
bash ./plop/runplop.sh championClass Rammus
bash ./plop/runplop.sh championClass RekSai
bash ./plop/runplop.sh championClass Rell
bash ./plop/runplop.sh championClass Renata
bash ./plop/runplop.sh championClass Renekton
bash ./plop/runplop.sh championClass Rengar
bash ./plop/runplop.sh championClass Riven
bash ./plop/runplop.sh championClass Rumble
bash ./plop/runplop.sh championClass Ryze
bash ./plop/runplop.sh championClass Samira
bash ./plop/runplop.sh championClass Sejuani
bash ./plop/runplop.sh championClass Senna
bash ./plop/runplop.sh championClass Seraphine
bash ./plop/runplop.sh championClass Sett
bash ./plop/runplop.sh championClass Shaco
bash ./plop/runplop.sh championClass Shen
bash ./plop/runplop.sh championClass Shyvana
bash ./plop/runplop.sh championClass Singed
bash ./plop/runplop.sh championClass Sion
bash ./plop/runplop.sh championClass Sivir
bash ./plop/runplop.sh championClass Skarner
bash ./plop/runplop.sh championClass Sona
bash ./plop/runplop.sh championClass Soraka
bash ./plop/runplop.sh championClass Swain
bash ./plop/runplop.sh championClass Sylas
bash ./plop/runplop.sh championClass Syndra
bash ./plop/runplop.sh championClass TahmKench
bash ./plop/runplop.sh championClass Taliyah
bash ./plop/runplop.sh championClass Talon
bash ./plop/runplop.sh championClass Taric
bash ./plop/runplop.sh championClass Teemo
bash ./plop/runplop.sh championClass Thresh
bash ./plop/runplop.sh championClass Tristana
bash ./plop/runplop.sh championClass Trundle
bash ./plop/runplop.sh championClass Tryndamere
bash ./plop/runplop.sh championClass TwistedFate
bash ./plop/runplop.sh championClass Twitch
bash ./plop/runplop.sh championClass Udyr
bash ./plop/runplop.sh championClass Urgot
bash ./plop/runplop.sh championClass Varus
bash ./plop/runplop.sh championClass Vayne
bash ./plop/runplop.sh championClass Veigar
bash ./plop/runplop.sh championClass Velkoz
bash ./plop/runplop.sh championClass Vex
bash ./plop/runplop.sh championClass Vi
bash ./plop/runplop.sh championClass Viego
bash ./plop/runplop.sh championClass Viktor
bash ./plop/runplop.sh championClass Vladimir
bash ./plop/runplop.sh championClass Volibear
bash ./plop/runplop.sh championClass Warwick
bash ./plop/runplop.sh championClass Xayah
bash ./plop/runplop.sh championClass Xerath
bash ./plop/runplop.sh championClass XinZhao
bash ./plop/runplop.sh championClass Yasuo
bash ./plop/runplop.sh championClass Yone
bash ./plop/runplop.sh championClass Yorick
bash ./plop/runplop.sh championClass Yuumi
bash ./plop/runplop.sh championClass Zac
bash ./plop/runplop.sh championClass Zed
bash ./plop/runplop.sh championClass Zeri
bash ./plop/runplop.sh championClass Ziggs
bash ./plop/runplop.sh championClass Zilean
bash ./plop/runplop.sh championClass Zoe
bash ./plop/runplop.sh championClass Zyra